apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value of 'password'
